# Generated by Django 4.2.4 on 2023-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idgoal', models.CharField(max_length=6)),
                ('Start', models.CharField(max_length=100)),
                ('stop', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'goal',
            },
        ),
    ]
