# Generated by Django 4.2.4 on 2023-08-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0002_rename_start_goal_start_alter_goal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='idgoal',
        ),
    ]
