# Generated by Django 4.2.4 on 2023-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0006_alter_goal_goal_alter_goal_start_alter_goal_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(max_length=50),
        ),
    ]
