# Generated by Django 4.2.4 on 2023-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0007_alter_goal_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='stop',
            field=models.CharField(max_length=100),
        ),
    ]
