# Generated by Django 4.2.4 on 2023-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0008_alter_goal_start_alter_goal_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='stop',
            field=models.DateField(),
        ),
    ]
