# Generated by Django 4.2.4 on 2023-08-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0009_alter_goal_start_alter_goal_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='null'),
        ),
    ]
